name: CI

on:
  push:
  pull_request:

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ruff (lint)
        run: ruff check .
      - name: Mypy (type check)
        run: mypy app
      - name: Pytest
        run: pytest -q

  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: edps-mlops-demo:ci
      - name: Trivy scan (optional)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: image
          image-ref: edps-mlops-demo:ci
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  # Uncomment to push to GHCR (set CR_PAT in repo secrets)
  # push-ghcr:
  #   needs: build-container
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.CR_PAT }}
  #     - uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}/edps-mlops-demo:latest
